//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileSystemControl.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileSystemControl.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время создания:.
        /// </summary>
        internal static string creationTime {
            get {
                return ResourceManager.GetString("creationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл с таким именем существует..
        /// </summary>
        internal static string fileExists {
            get {
                return ResourceManager.GetString("fileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл перенесли в папку.
        /// </summary>
        internal static string fileMovedFolder {
            get {
                return ResourceManager.GetString("fileMovedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл создан:.
        /// </summary>
        internal static string fileСreated {
            get {
                return ResourceManager.GetString("fileСreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локализация не найдена. Продолжаем работать в локализации по умолчанию..
        /// </summary>
        internal static string localizationEmpty {
            get {
                return ResourceManager.GetString("localizationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to новое название:.
        /// </summary>
        internal static string newName {
            get {
                return ResourceManager.GetString("newName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл переименовали, старое название:.
        /// </summary>
        internal static string oldName {
            get {
                return ResourceManager.GetString("oldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список шаблонов обработки пуст..
        /// </summary>
        internal static string templateEmpty {
            get {
                return ResourceManager.GetString("templateEmpty", resourceCulture);
            }
        }
    }
}
